### PR TITLE
v2.3.15: 新增插件DebugTopicFilterPlugin，校验异常类及其相应的异常处理策略 (ignore, debug, …

### PR DESCRIPTION
**Pull request by hect0x7**
…raise)。修复移动端未携带cookies导致跳转同本问题。

## Summary by CodeRabbit

Release Notes:

New Features:
- Introduced `pycryptodome` and `requests` packages to enhance functionality.
- Added `fetch_init_cookies` method for initial cookie retrieval.
- Introduced `PluginValidationException` class for improved error handling.
- Added `validate_params` method for parameter validation in plugins.
- Introduced `DebugTopicFilterPlugin` class for filtering debug messages.

Bug Fixes:
- Fixed potential issues in `delete_all_files_and_empty_dir` method by checking file or directory existence before removal.
- Improved `login` method by ensuring headers are always set.

Refactor:
- Renamed `MAGIC_18COMICAPPCONTENT` to `APP_SECRET` for clarity.
- Updated `new_postman` function to include a new 'valid'-'debug' pair.
- Modified `new_jm_client` function to handle `PluginValidationException`, `JmcomicException`, and other exceptions separately.

Chores:
- Updated version number from '2.3.14' to '2.3.15'.
- Removed `JmDownloadException` class.

### CODE REVIEW

**Comment by hect0x7** [comment]
@coderabbitai review

**Comment by buiawpkgew1** [comment]
> @coderabbitai review

你这个可以自动coderabbitai review

**Comment by hect0x7** [comment]
@coderabbitai review 
i submit a new commit to fix. what about now?

**Comment by hect0x7** [comment]
@coderabbitai review

**Pull request merged**
